debug: false

server:
  port: 8080

spring:
  application:
    name: quizz
  shell:
    interactive:
      enabled: false
    script:
      enabled: false
    history:
      enabled: false
      name:
  output:
    ansi:
      enabled: ALWAYS

logging:
  level:
    root: INFO
    '[software.amazon.awssdk]': INFO
    '[org.apache.http]': INFO

profanity:
  custom-words: badword1,badword2

session-code:
  seed: 12345
  length: 6
  dictionary: "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"

pictures-s3:
  host: ${APP_S3_HOST:localhost}
  port: ${APP_S3_PORT:9190}
  public-endpoint: ${APP_S3_PUBLIC_ENDPOINT:http://localhost:9190}
  bucket-name: ${APP_S3_BUCKET_NAME:quezap-public-images}
  access-key-id: ${APP_S3_ACCESS_KEY_ID:quezap_java_writer}
  secret-access-key: ${APP_S3_SECRET_ACCESS_KEY:LocalPassword}

jwt:
  secret-key: ${APP_JWT_SECRET_KEY:4a3c4e58311739e4a396ad7a38a5454ad65cfde67b0fef9aeb351cbb3c478fef}
  issuer: ${APP_JWT_ISSUER:quezap.com}

participation:
  token-expiration-seconds: 3600
